update 4.0.5 release

diff --git a/po-man/Makefile.in b/po-man/Makefile.in
--- a/po-man/Makefile.in
+++ b/po-man/Makefile.in
@@ -17,10 +17,12 @@
 # *.po and *.pot are kept in VCS and generated by po4a-dist command
 # translated/* are put in distribution but not found in VCS
 #
-# run:
+# To update man page translations:
 #   rm po-man/man.stamp
 #   make -C po-man man.stamp
-# To update man page translations
+#
+# To update the po and pot files:
+#   make -C po-man update-po
 VPATH = @srcdir@
 am__is_gnu_make = { \
   if test -z '$(MAKELEVEL)'; then \
@@ -511,7 +513,11 @@ all-local-yes: man.stamp
 
 # FIXME: Use a stamp file until po4a supports them internally.
 man.stamp:
-	$(PO4A_V) $(PO4A) $(PO4A_OPTS) $(srcdir)/po4a.cfg
+	@if test -z '$(PO4A)'; then \
+		echo "error: You need to install the po4a package."; \
+		exit 1; \
+	fi
+	$(PO4A_V) $(PO4A) $(PO4A_OPTS) --no-update $(srcdir)/po4a.cfg
 	$(AM_V_at) touch $@
 
 clean-local: clean-local-@USE_PO4A@
@@ -529,7 +535,11 @@ procps-man.pot: $(src_MANS)
 	po4a-gettextize -M utf8 --option groff_code=verbatim --option generated --option untranslated="a.RE,\|" --option unknown_macros=untranslated -f man $(patsubst %,-m%,$(subst :, ,$(src_MANS))) -p $@
 
 update-po:
-	$(PO4A_V) $(PO4A) $(PO4A_OPTS) --force $(srcdir)/po4a.cfg
+	@if test -z '$(PO4A)'; then \
+		echo "error: You need to install the po4a package."; \
+		exit 1; \
+	fi
+	$(PO4A_V) $(PO4A) $(PO4A_OPTS) --no-translations --force $(srcdir)/po4a.cfg
 
 install-data-local:
 	for lang in $(LINGUAS) ; do \
